# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Compute the inverse of a matrix
#'
#'@param A a matrix
#'
#'
invC <- function(A) {
    .Call(`_mypkgr_invC`, A)
}

timesTwo <- function(x) {
    .Call(`_mypkgr_timesTwo`, x)
}

